[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mypackage"
version = "0.0.6"
dependencies = [
    "requests",
]

[project.scripts]
cli-name = "mypackage.main:main"
